#!/bin/bash

./helper41 &
./helper42 &
./helper43 &

pid1=$(pgrep helper41)
pid3=$(pgrep helper43)

if [[ ! "$pid3" ]]; then
    echo "Process 'helper43' not found."
    exit 1
fi

kill -TERM $pid3 || { 
	echo "Faile";
	 exit 1; 
}

cpulimit -p $pid1 -l 10 -z || { 
	echo "Faile"; 
	exit 1;
 }
