#!/bin/bash

gamma_function() {
    local x=$1
    local result=1
 for ((i = 1; i <= x; i++)); do
                result=$((result + i))
        done

    result=$(echo "scale=10; l($x) + gamma" | bc -l)


}

export -f gamma_function

seq "$1" | parallel -j 0 gamma_function
