#!/bin/bash

N_LIST=(10 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 190 200)

for N in "${N_LIST[@]}"; do
  
	for ((i = 1; i <= 20; i++)); do
   		 /usr/bin/time -f "%E" -o "ans11/tmp${i}.txt" ./gamma "$N"
    		tail -n 1 "ans11/tmp${i}.txt" >> "ans11/result_1_${i}.txt"
	done
done
