#!/usr/bin/bash

fileread() {
	filename="bigData/file_$1.txt"
	while read -r value; do
		new_value=$((value * 2))
		echo "$new_value" >>"ans22/$1.txt"
	done <"$filename"
}
export -f fileread 

seq "$1" | parallel -j 0 fileread
